### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by Zero-in** [mkbrutusproject/MKBRUTUS#1]
If a dict doesn't fit in memory while charging buffer :
# 
## +1: [*] Starting bruteforce attack...

Traceback (most recent call last):
  File "./mkbrutus.py", line 364, in <module>
    main()
  File "./mkbrutus.py", line 297, in main
    buffer = dictFile.read(8192*1024)
  File "/opt/lib/python3.2/codecs.py", line 679, in read
    return self.reader.read(size)
  File "/opt/lib/python3.2/codecs.py", line 495, in read
    self.charbuffer += newchars
MemoryError
# 

I was running brutus on my router with 200mb of free ram, no swap. With 130Mb rockyou.txt
It might be usefull to  make it read big dicts in chunks to prevent the crushes.

Kind regards - Peter Zhakov
Russia Saint-Petersburg.

**Comment by rcaire** [comment]
Hi Peter!
Apologies for my late response, I was on holidays.
Good advice, but the point is that MKBRUTUS wasn't made to run on small
devices but computers with a reasonable amount of RAM. I was running
rockyou.txt of more than 150 MB without problems.
But yeap, it's a good idea to run the tool from a small device, like a
small router or a Raspberry Pi. I'll take into account in future releases.

Thanks a lot for the feedback!
cheers
Ramiro

On Fri, Jan 23, 2015 at 5:58 AM, Zero-in notifications@github.com wrote:

> If a dict doesn't fit in memory while charging buffer :
> 
> [code]
> +1: [*] Starting bruteforce attack...
> 
> Traceback (most recent call last):
> File "./mkbrutus.py", line 364, in
> main()
> File "./mkbrutus.py", line 297, in main
> buffer = dictFile.read(8192*1024)
> File "/opt/lib/python3.2/codecs.py", line 679, in read
> return self.reader.read(size)
> File "/opt/lib/python3.2/codecs.py", line 495, in read
> self.charbuffer += newchars
> MemoryError
> [/code]
> I was running brutus on my router with 200mb of free ram, no swap. With
> 130Mb rockyou.txt
> It might be usefull to make it read big dicts in chunks to prevent the
> crushes.
> 
> Kind regards - Peter Zhakov
> Russia Saint-Petersburg.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mkbrutusproject/MKBRUTUS/issues/1.

## 

Ramiro J. Caire

E-mail: ramiro.caire@gmail.com
PGP: 0xA657B4362D357BEC
Sitio: seguridadetica.wordpress.com
Twitter: @rcaire

**Comment by gavz** [comment]
python.exe mkbrutus.py -t 192.168.1.1 -p 22 -u admin -d "D:\wordlist\uniq.lst"
with 12Gb ram I got an error :

Traceback (most recent call last):
  File "mkbrutus.py", line 363, in <module>
    main()
  File "mkbrutus.py", line 302, in main
    for password in dictFile.readlines():
  File "C:\Python35\lib\codecs.py", line 706, in readlines
    return self.reader.readlines(sizehint)
  File "C:\Python35\lib\codecs.py", line 615, in readlines
    data = self.read()
  File "C:\Python35\lib\codecs.py", line 493, in read
    newdata = self.stream.read()
MemoryError

file size -> uniq.lst - 2,47Gb
