### ISSUE TITLE
Mikrotic OS 6x problem.

### ISSUE THREAD

**Issue by JackZaitsev** [mkbrutusproject/MKBRUTUS#7]
Posting the entire error here, hopping its some mistake I made :) 

`sudo python3 mkbrutus.py -t 192.168.123.10 -p 9090 -d /home/jack/Downloads/Lists/nomes.txt
          _   _   _   _  _____  ____ _   _  ____ _   _ _____
         |  \/  || | / /| ___ \ ___ \ | | |_   _| | | /  ___|
         | .  . || |/ / | |_/ / |_/ / | | | | | | | | \`--.
         | |\/| ||    \ | ___ \    /| | | | | | | | | |`--. \
         | |  | || |\  | |_/ / |\ | |_| | | | | |_| /__/ /
         _|  |_/\_| _/_**_/\_| _|_**/  _/  _**/__**/

```
                  Mikrotik RouterOS Bruteforce Tool 1.0.2
       Ramiro Caire (@rcaire) & Federico Massa (@fgmassa)
                http://mkbrutusproject.github.io/MKBRUTUS
```
## [*] Starting bruteforce attack...

Traceback (most recent call last):
  File "mkbrutus.py", line 363, in <module>
    main()
  File "mkbrutus.py", line 329, in main
    defaultcreds = apiros.login("admin", "")
  File "mkbrutus.py", line 103, in login
    for repl, attrs in self.talk(["/login"]):
  File "mkbrutus.py", line 116, in talk
    i = self.readSentence();
  File "mkbrutus.py", line 140, in readSentence
    w = self.readWord()
  File "mkbrutus.py", line 149, in readWord
    ret = self.readStr(self.readLen())
  File "mkbrutus.py", line 178, in readLen
    c = ord(self.readStr(1))
  File "mkbrutus.py", line 219, in readStr
    s = self.sk.recv(length - len(ret))
socket.timeout: timed out
`
edit: it was my mistake, I was sending the port twice, so that was my mistake but this new error does not seem to be, apparently there is another issue open on the timeout problem, so if instructed I will close this one.

**Comment by rcaire** [comment]
Hi,

the port 9090 belongs to API port or Winbox port?

cc @lisogallo
